### ISSUE TITLE
Port Authority naming format

### ISSUE THREAD

**Issue by BHuffs** [NYCPlanning/db-pluto#100]
Port Authority was not upgraded to a new naming format, and so they are multiple values for the same agency on the OwnerName column.  As a quick check I found 38 lots with 6 variations of Port Authority name in Manhattan.  I am attaching an Excel that has the 38 lots I found but this should be cross checked with Port Authority, they may have a master list that includes all BBLs they own.

[Port Authority Lots.xlsx](https://github.com/NYCPlanning/db-pluto/files/3968731/Port.Authority.Lots.xlsx)

**Comment by AmandaDoyle** [comment]
Added these owner names to the pluto_input_research csv
