### ISSUE TITLE
Zoning District 1: Ignore the 10% rule when zoning district 1 is NULL

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#101]
There are waterfront lots that have a NULL Zoning District 1 value

For cases where Zoning District 1 is NULL, ignore the 10% rule and and assign the zoning district that covers most of the lot as zoning district 1

**Comment by SPTKL** [comment]
```sql
UPDATE pluto a
SET zonedist1 = zonedist
FROM lotzoneperorder b
WHERE a.bbl=b.bbl 
  AND a.zonedist1 is null
  AND row_number = 1;
```

fixed
