### ISSUE TITLE
Data Quality, vacant lot is listed having built area.

### ISSUE THREAD

**Issue by bpachuca** [NYCPlanning/db-pluto#105]
The lot under land use vacant lot has a building area of 24,632 sqft. When spot checked using Google Maps seems to still be a vacant lot with no new building area.

## BBL: Queens 9767-61

[zola link](https://zola.planning.nyc.gov/l/lot/4/9767/61?aerial-year=aerials-2016&layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D&print=false&selectedOverlays=%5B%22C1-1%22%2C%22C1-2%22%2C%22C1-3%22%2C%22C1-4%22%2C%22C1-5%22%2C%22C2-1%22%2C%22C2-2%22%2C%22C2-3%22%2C%22C2-4%22%2C%22C2-5%22%5D&selectedZoning=%5B%22BP%22%2C%22C1%22%2C%22C2%22%2C%22C3%22%2C%22C4%22%2C%22C5%22%2C%22C6%22%2C%22C7%22%2C%22C8%22%2C%22M1%22%2C%22M2%22%2C%22M3%22%2C%22PA%22%2C%22R1%22%2C%22R10%22%2C%22R2%22%2C%22R3%22%2C%22R4%22%2C%22R5%22%2C%22R6%22%2C%22R7%22%2C%22R8%22%2C%22R9%22%5D&shouldRefresh=false#19.09/40.7067395/-73.7990411)

**Comment by AmandaDoyle** [comment]
@bpachuca thanks for bringing this to our attention

Note to self: There are 28 records that are marked as vacant but have a building area.  We need to talk to providers of source data
