### ISSUE TITLE
Number of buildings is incorrect for condo lots with multiple buildings

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#129]
If the tax lot is in Geosupport, the Geosupport Number of Structures field is used. If the tax lot is not found in Geosupport, the number of buildings value is taken from PTS

It looks like we might be taking the number of structures from the address call and not the BL call

For example lot 3044237501
PLUTO says 1 structure
GOAT for a BL call says 19 structures

**Comment by SPTKL** [comment]
http://a030-goat.nyc.gov/goat/Function1A?borough=3&street=JEROME%20STREET&address=971

**Comment by SPTKL** [comment]
https://geosupport.herokuapp.com/geocode/bl?bbl=3044237501
Geosuport bl function still gives 1 as number of structures

**Comment by SPTKL** [comment]
![image](https://user-images.githubusercontent.com/13207770/75192153-b2970380-5721-11ea-9627-9182bb76923c.png)

**Comment by AmandaDoyle** [comment]
Corrected in generation of 20v2 on GeoSupport 20A
