### ISSUE TITLE
Check for invalid geometries after clipping

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-pluto#137]
For example: BBL 4004890023 has invalid geometry for clipped version of mappluto.

**Comment by SPTKL** [comment]
we are now enforcing valid geometry using `st_makevalid`
https://github.com/NYCPlanning/db-pluto/blob/ca0ecaa03aa83ebfad12ab3e8d0f70e7099a3232/pluto_build/sql/export.sql#L96-L112
