### ISSUE TITLE
Improvement: Irregular lot code - regular to irregular

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#146]
Identify lots where the irregular lot code should be changed from regular to irregular

Recreate [Ann's work](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/DATA%20ENGINEERING/Ann%27s%20Research/IrrLotCode?csf=1&web=1&e=G43qQg) within the PLUTO workflow.  This would be a QAQC output where the proposed records to correct would be reviewed before implementing changes

Though, based on [Lynn's feedback](https://nyco365.sharepoint.com/:f:/r/sites/NYCPLANNING/itd/edm/Shared%20Documents/PROJECTS/DATA%20ENGINEERING/Ann%27s%20Research/IrrLotCode/Lynn%27s%20review?csf=1&web=1&e=jWbX41) be more conservative about changing lots from regular to irregular.  Screenshots are lots that should remain regular and spreadsheet is her review of a subset of AM's work (lots that should stay regular, could be regular or irregular, are definitely irregular

**Comment by mgraber** [comment]
Consider implementing a simple binary classifier.
Potential features: number of points, the distance between points, angles at each point...
