### ISSUE TITLE
Improvement: number of buildings

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#148]
Run DoITT building footprint BIN through GeoSupport BN to get BBL and then use that

**Comment by SPTKL** [comment]
this is incorporated, but still need to verify through QAQC

**Comment by SPTKL** [comment]
![image](https://user-images.githubusercontent.com/13207770/81734045-eea84d80-9460-11ea-8e60-00ed7f37306b.png)
1.88% of records saw a change
