### ISSUE TITLE
v6 - enhancement: add in DPR Green Thumb gardens

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#161]
Vacant lots that have a green thumb garden will have their land use value updated.  These corrections will be made via the manual corrections table, and the additions to manual corrections table will be supplied by LS.

https://github.com/NYCPlanning/db-pluto/compare/master...gardens

**Comment by AmandaDoyle** [comment]
Committed code to facilitate setting Building class to QG

**Comment by SPTKL** [comment]
Is this ready for PR?

**Comment by SPTKL** [comment]
https://github.com/NYCPlanning/db-pluto/commit/78ca2abb541bbf1aa9853409ad9497493998897a
