### ISSUE TITLE
Source data updates from Open Data

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#198]
- [x] Greenthumb
[Greenthumb garden information](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.cityofnewyork.us%2Fdataset%2FGreenthumb-Garden-Info%2Fp78i-pat6&data=04%7C01%7CADoyle%40planning.nyc.gov%7C423fce54b4844de04b2a08d8964d92b6%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C637424607196454187%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZyoxkaO%2BLUCPLmBj6FU%2FvMV5BIdVgMGaSyHsBN0yNHY%3D&reserved=0), and [corresponding block/lot data for each garden](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.cityofnewyork.us%2Fdataset%2FGreenthumb-Block-Lot%2Ffsjc-9fyh&data=04%7C01%7CADoyle%40planning.nyc.gov%7C423fce54b4844de04b2a08d8964d92b6%7C32f56fc75f814e22a95b15da66513bef%7C0%7C0%7C637424607196464146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xZAgWNotmac3wDTyvWtBLrVYvkWm%2FeRe%2FfOu%2Fsy9bw4%3D&reserved=0).

**Comment by SPTKL** [comment]
data updated through recipe app, closing
