### ISSUE TITLE
In latest version of PLUTO 21v2 there are no records with bldgclass QG

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#260]
In latest version of PLUTO 21v2 there are no records with bldgclass QG

[This section](https://github.com/NYCPlanning/db-pluto/blob/37cdf16ecdf2c29e964d386aab233c73c94fc214/pluto_build/sql/bldgclass.sql#L100) of code does not return anything.  There are records where the building class starts with V.  Maybe there is an issue with the gardens layer projection?  AD needs to investigate and look at the output.

**Comment by SPTKL** [comment]
reran complete with updated source data
