### ISSUE TITLE
BBLs 3026150001-0050 is showing incorrect zoning districts

### ISSUE THREAD

**Issue by rtblair** [NYCPlanning/db-pluto#265]
TRD points out that block 2615 is correctly zoned M1-5, but lots 1-50 are all showing up with the older zoning (m3-1) in ZoLa, which has been updated with all the latest data. [Example: Lot 19](https://zola.planning.nyc.gov/l/lot/3/2615/19?aerial-year=aerials-2016&layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D&print=false&search=false&selectedOverlays=%5B%22C1-1%22%2C%22C1-2%22%2C%22C1-3%22%2C%22C1-4%22%2C%22C1-5%22%2C%22C2-1%22%2C%22C2-2%22%2C%22C2-3%22%2C%22C2-4%22%2C%22C2-5%22%5D&selectedZoning=%5B%22BP%22%2C%22C1%22%2C%22C2%22%2C%22C3%22%2C%22C4%22%2C%22C5%22%2C%22C6%22%2C%22C7%22%2C%22C8%22%2C%22M1%22%2C%22M2%22%2C%22M3%22%2C%22PA%22%2C%22R1%22%2C%22R10%22%2C%22R2%22%2C%22R3%22%2C%22R4%22%2C%22R5%22%2C%22R6%22%2C%22R7%22%2C%22R8%22%2C%22R9%22%5D&shouldRefresh=false#20.3/40.7250409/-73.9556966)

**Comment by AmandaDoyle** [comment]
@rtblair in PLUTO 21v2 the zonedist1 value is `M1-5` for these lots
21v1 has a zonedist1 value of `M3-1`
PLUTO needs to be updated in ZoLa

![Screen Shot 2021-07-02 at 12 26 08 PM](https://user-images.githubusercontent.com/5611960/124303695-b9613200-db30-11eb-9a30-10ecc95c658a.png)

**Comment by rtblair** [comment]
Thanks for the clarification! Closing.
