### ISSUE TITLE
Fix source data ingestion to include/exclude water

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-pluto#267]
## To-do
dcp_cdboundaries -- > dcp_cdboundaries_wi
dcp_censustracts --> dcp_censustracts_wi
dcp_censusblocks --> dcp_censusblocks_wi
dcp_councildistricts --> dcp_councildistricts_wi

---
Spent some more time with this.  

On Mar 30 we started switching data loading from fastloading.py to import from data library.  This is when we came up with the convention that `_wi`would indicate that a spatial boundary included water.  Before this convention it was a hodgepodge and often no suffix indicating that water was included and `_wo` indicating a dataset was without water.  

Many of the dataset coming from fastloading included water, but were not suffixed.  

We need to update the spatial boundaries from data library to include the version with water (`_wi`) where a version with water exists.  This should be applicable for:
- dcp_cdboundaries 
- dcp_censustracts 
- dcp_censusblocks 
- dcp_councildistricts 

Fix this for 21v3

_Originally posted by @AmandaDoyle in https://github.com/NYCPlanning/db-pluto/issues/261#issuecomment-864283956_

@AmandaDoyle  can you confirm for pluto do we need water or no? Also this change would have down stream impact on other data product. can you do an audit before we make the change?

**Comment by AmandaDoyle** [comment]
@SPTKL  Flagging this as something for us to discuss because I don't know what downstream impacts you're thinking of.

**Comment by SPTKL** [comment]
@AmandaDoyle https://github.com/NYCPlanning/db-pluto/issues/261

**Comment by AmandaDoyle** [comment]
@SPTKL  Yes we need to use the version with water for the following boundaries 

dcp_cdboundaries -- > dcp_cdboundaries_wi
dcp_censustracts --> dcp_censustracts_wi
dcp_censusblocks --> dcp_censusblocks_wi
dcp_councildistricts --> dcp_councildistricts_wi

**Comment by AmandaDoyle** [comment]
Resolved with issue #282
