### ISSUE TITLE
21v3 review

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#276]
- [x] No "QG/09" building class / land use value
QG is missing as a building class value.  Did the parks gardens layer not load properly again?

- [x] need to investigate
What's going on with the loss in factory area?
Factory area seems to be right, but in 21v2 all area came from PTS, and not from CAMA, which explains the changes
See sum of factryarea by source

**v1**
2 (PTS) 99911455
4	126300
7 (CAMA) 1433456
**v2**
2 	116991566
7	0
**v3**
2	99777640
4	0	
7	1226012

**Comment by AmandaDoyle** [comment]
Still no "QG/09" building class / land use value

**Comment by SPTKL** [comment]
21v3 is published and released
