### ISSUE TITLE
Update year built values where yearbuilt <1600 and <> 0 and it doesn't come from LPC

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-pluto#294]
User found records where yearbuilt <1600 and <> 0 and it doesn't come from LPC.  
- [x] Set the yearbuilt value to 0.

**Comment by AmandaDoyle** [comment]
[LPC_yearBuilt_upds.csv.zip](https://github.com/NYCPlanning/db-pluto/files/7557201/LPC_yearBuilt_upds.csv.zip)
 Add research to manual correction file

**Comment by AmandaDoyle** [comment]
@lseirup  We need to discuss how you envision the workflow for setting `yearbuilt` to 0 for records where `yearbuilt <1600 and <> 0`.  Here are the options:
1) Programmatically set yearbuilt to 0 for all records where `yearbuilt <1600 and <> 0` and do not keep a change log
2) Using 21v3 as the reference add records to the manual corrections file (easiest for a quick solution)
3)  Programmatically set yearbuilt to 0 for all records where `yearbuilt <1600 and <> 0` and add to change log (most in line with other corrections we make)
4) Other

Let me know what you think.

**Comment by lseirup** [comment]
@AmandaDoyle Let's take the easy approach and go with option 2. I think that any new construction will have a year built value, so we're unlikely to get new zero values
