### ISSUE TITLE
cscl lat/long in test build of pluto (instead of bbl centroid lat/long)

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-pluto#311]
When we built a test of PLUTO 21v4, we were getting different lat/long than previous versions of PLUTO because the geocode.py process was geocoding records to the street centerline point instead of the bbl centroid.

**Comment by SashaWeinstein** [comment]
I did some research on what extended mode does and found this page on the [extended work option modes](https://nycplanning.github.io/Geosupport-UPG/chapters/chapterII/section12/). It says that the extended work option includes "New data (e.g. CSCL data)" which we saw from its behavior ❌ 😞 . But it also says that "Some other data that may be included in the Extended Work Areas are: Health Center District, NTA Name (Neighborhood Tabulation Area Name), PUMA Code (Public Use Microdata Area Code)" and we see that `ct2020` and `cb2020` is included in these "some other data" ✅ 👍 . Baiyue's solution involved combining results from regular mode and extended work option mode but in the wrong order, overwriting regular with extended which overwrote the good lat/longs. We want to overwrite extended with regular so the good lat/longs stick around. 

While working on this problem I got curious about the progression from 1A/1E function to 1B to BBL
I am doing research on which function to use and found this [geosupport documentation](https://nycplanning.github.io/Geosupport-UPG/chapters/chapterV/section04/#function-1a) on address geocoding functions. What I learned is that 1B combines extended versions of 1A and 1E which we don't want as we need both extended and non-extended versions. So 1B is coming out. I also see that 1E and 1A differ on exactly *one* address in the city, 3333 broadway. I don't know if it's worth keeping 1A if it only geocodes one address in the whole city more correctly. @AmandaDoyle curious if you think I'm interpreting this correctly.

Next steps are taking out 1B and trying 1E first in the progression.
