### ISSUE TITLE
shp file export 

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-pluto#332]
22v1 [PLUTO build failed](https://github.com/NYCPlanning/db-pluto/runs/6478857693?check_suite_focus=true) with the following error
```
ERROR 1: ERROR:  column s.consrc does not exist
LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
                                                             ^
HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".
```
according to [this post](https://gis.stackexchange.com/questions/342246/ogr2ogr-from-file-to-postgresql-12-table-fails) this is likely a gdal version issue.

**Comment by SashaWeinstein** [comment]
Oh yea I kept getting this as well, couldn't find a solution

**Comment by td928** [comment]
> Oh yea I kept getting this as well, couldn't find a solution

my idea atm is to get rid of the docker image and build gdal on ubuntu and run exporting. Creating a local devcontainter to test this now

**Comment by SashaWeinstein** [comment]
I see how that makes sense for local development, how would it work on github actions though?

**Comment by td928** [comment]
I am basing the devcontainer setup on the [facdb devcontainer](https://github.com/NYCPlanning/db-facilities/tree/develop/.devcontainer) and assuming for action build I can [follow suite as well](https://github.com/NYCPlanning/db-facilities/actions/runs/2346240296/workflow)?

**Comment by SashaWeinstein** [comment]
the facDB setup is a more complicated docker setup than any other I have seen yet, it uses docker compose to get two containers to work together. no other data product does that, they use docker run --rm etc

**Comment by td928** [comment]
Okay reporting back on this. Setting up the environment was a success but very ironic we are in a wack of mole situation that FileGDB flares up again for the gdb exporting step. It is a [well documented issue](https://github.com/geopandas/geopandas/issues/868) with gdal that does not have very good solution on except to [build gdal with geodatabase driver](https://github.com/Esri/file-geodatabase-api/blob/master/FileGDB_API_1.5.2/FileGDB_API_RHEL7_64.tar.gz). Lack a good documentation on how to do that seems like the main challenge. I have more less given up hope that we can find a one size fits all solution for this but instead I think we have to resolve to use one workflow for gdb and one for shapefile as a work around.

**Comment by SashaWeinstein** [comment]
I definitely want to hear more about this at standup, still pretty confused
