### ISSUE TITLE
FireComp losing prefix letter

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/db-pluto#34]
Codes for Fire Companies seem to be losing Ladder and Engine letter prefixes. See below

FireComp Field Ex Production 18v1.1 - L029, E060, etc
FireComp Field Ex Development 18v2 - 029, 060, etc

Example BBL where occurrence is observed - 2022610032

**Comment by AmandaDoyle** [comment]
Corrected with new goecoded data
