### ISSUE TITLE
ProxCode contains 'N' values rather than NULLs

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/db-pluto#36]
ProxCode Data Dictionary lists acceptable fields as follows:

0 Not Available
1 Detached
2 Semi-Attached
3 Attached

However, values of 'N' appear in 18v2 draft release. Noticed this while working on domains because they had no description for this specific coded value.

Example record BBL as follows: 2048280031

**Comment by AmandaDoyle** [comment]
Removed N records from CAMA input data
