### ISSUE TITLE
Corrections Not Applied Report

### ISSUE THREAD

**Issue by abrieff** [NYCPlanning/db-pluto#368]
Required by https://github.com/NYCPlanning/data-engineering-qaqc/issues/49, we need a new report in PLUTO that tracks corrections not applied.

Questions to be answered:

1. Should this be included in pluto_corrections.zip, which is hosted on opendata as the Pluto Change file?
2. Should the pluto corrections applied and not applied be packaged as one table like devdb does with corrections reference?
3. With the desire to compare corrections across versions of pluto, should the report include corrections applied and not applied across multiple versions of pluto?

**Comment by Oysters1874** [comment]
I feel like it makes sense to include the corrections not applied in the pluto_corrections.zip folder. Not sure about how the specific logic of devdb dealing with corrections, but I think for pluto, maybe we can separate them into two tables. For the third question, I think we'd better first think about how we want the qaqc page structured. 
As for the outlier report, we are asked to sort out BBLs with 50+ unitsres and resarea/unitsres < 300 etc, I feel like it makes more sense if we just display the outlier for the current version. And for the correction report, I think it will be much neater if we just include the correction applied/ not applied for this version. It doesn't need to really involve comparison between versions at least in this correction report section. Just my thoughts. I am still curious about how we are going to organize every part and tie them together.

**Comment by mbh329** [comment]
1. Yes, they should be packaged as one zip file.
2. I think if its a big lift to amalgamate the table like dev-db then we can hold off for now and just have the corrections applied and not applied tables as separate tables. @td928  is a good resource here as he has the most exp. with dev-db 
3. Need to look into this as I am not quite sure atm
