### ISSUE TITLE
Full Address Missing for some records

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/db-pluto#37]
Example observed in mappluto production:
Address - '500 ST ANNS AVENUE'
BBL - 2022600193

Example observed in mappluto 18v2 draft
Address - '500'
BBL - 2022600193

Only witnessed this particular issue for 1 record, but have not implemented a programmatic check as of yet.

**Comment by AmandaDoyle** [comment]
Changed street name input from boepreferredstreetname to street_name
