### ISSUE TITLE
GDB links are downloading as unzipped

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/db-pluto#385]
Mappluto.gdb and Mappluto_unclipped.gdb download links on the main pluto readme are downloading improperly (e.g. mappluto_unclipped_gdb.gbd.zip, mappluto_gdb.gdb.zip).  Matt says these used to download as zips but now because the .gdb suffix comes first, file explorer is only recognizing them as gdbs. This is preventing a successful run of one of GIS's PLUTO scripts.

**Comment by td928** [comment]
Hey @caseysmithpgh would you mind point me to the link the script is currently fetching the file from?

**Comment by caseysmithpgh** [comment]
@td928 It's on Matt's computer, I'll grab it after data users mtg and send it over

**Comment by mbh329** [comment]
Older versions of pluto (< 21v4) wrote the gdb files in the output weirdly (e.g. `output/mappluto_gdb.gdb/mappluto_gdb.gdb.zip`) where it was essentially nesting a .gdb.zip in another parent .gdb. During one of the more recent refactors of PLUTO, we corrected this and wrote the path to the gdb as `output/mappluto_gdb/mappluto_gdb.gdb.zip`. The ini script that GIS uses had the old file path for .gdb which obviously didn't work
