### ISSUE TITLE
AppDate/AreaSource issues 12/27 output

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/db-pluto#39]
AreaSource field seems to have lost some values that are present in Production (utilizing Bronx Definition Query)
Field - AreaSource
Production Values - "0", "2", "4", "5", "7"
18v2 Review Vals - NULL, "2"

AppDate field has had a change in date format
Field - AppDate
Prod Example - 09/08/2011
18v2 Review Vals - 09-08-2011

**Comment by AmandaDoyle** [comment]
resolved with apdate.sql and cama_bldgarea.sql
