### ISSUE TITLE
[build] version:  Minor: 23v1.1

### ISSUE THREAD

**Issue by mbh329** [NYCPlanning/db-pluto#441]
# Update version name

# PLUTO now uses version numbering YYvMAJOR.MINOR
1. YY for the last two digits of the release year
2. MAJOR version for using the latest versions of all input data
2. MINOR version for using the latest versions of particular input data

### Major Release: To initiate a major release, you must change the VERSION and VERSION_PREV. All other variables can remain unchanged and will default to latest in the dataloading step. 

- [ ] <https://github.com/NYCPlanning/db-pluto/blob/main/pluto_build/version.env>

### Minor Release: To initiate a minor release, you must change the VERSION and VERSION_PREV. In addition, you are required to hold the following variables constant with the last major release of PLUTO (you can reference the `source_data_version` table):

- [x] <https://github.com/NYCPlanning/db-pluto/blob/main/pluto_build/version.env>

- [x] DOF_WEEKLY_DATA_VERSION
- [x] DOF_CAMA_DATA_VERSION

- [x] GEOSUPPORT_VERSION
- [x] FEMA_FIRPS_VERSION
- [x] DOITT_DATA_VERSION
- [x] DOF_DATA_VERSION

- [x] DCP_COLP_VERSION
- [x] DPR_GREENTHUMB_VERSION
- [x] DSNY_FREQUENCIES_VERSION
- [x] LPC_HISTORIC_DISTRICTS_VERSION
- [x] LPC_LANDMARKS_VESRSION

- [x] PLUTO_CORRECTIONS_VERSION
# Data loading

#### Updated 2x a year typically in June and December
- [x] **dcp_colp** (check [here](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-colp.page)) 
#### Currently updated with each new release of a major version of PLUTO - important to make sure this is up to date
- [ ] **pluto_corrections** (pulling from bytes, must update when there's updates to **pluto_input_research**)

#### Open data automated pull

> Check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/open-data.yml) to see the latest run

- [x] **dsny_frequencies**
- [x] **dpr_greenthumb**
- [x] **lpc_historic_districts**
- [x] **lpc_landmarks**

#### DOF Automated Pull and Number of Buildings

- [ ] **pluto_pts** (Check [here](https://github.com/NYCPlanning/db-pluto/actions/workflows/input_pts.yml))
- [ ] **pluto_input_geocodes** (Check [here](https://github.com/NYCPlanning/db-pluto/actions/workflows/input_pts.yml))
- [ ] **pluto_input_cama_dof** (Check [here](https://github.com/NYCPlanning/db-pluto/actions/workflows/input_cama.yml))
- [ ] **pluto_input_numbldgs** (Check [here](https://github.com/NYCPlanning/db-pluto/actions/workflows/input_numbldgs.yml))

### Updated with Quarterly updates (check [here](https://github.com/NYCPlanning/db-data-library/actions/workflows/quaterly-updates.yml))

- [x] **dcp_cdboundaries_wi**
- [x] **dcp_ct2010**
- [x] **dcp_cb2010**
- [x] **dcp_ct2020**
- [x] **dcp_cb2020**
- [x] **dcp_school_districts**  
- [x] **dcp_councildistricts_wi**  
- [x] **dcp_firecompanies**  
- [x] **dcp_policeprecincts**
- [x] **dcp_healthareas**  
- [x] **dcp_healthcenters**

### Updated with Zoning Taxlots (check [here](https://github.com/NYCPlanning/db-zoningtaxlots/actions/workflows/dataloading.yml) for latest run). Note: for a minor release of PLUTO, these will be the only datasets that will be updated.

- [ ] **dof_dtm**
- [ ] **dof_shoreline**
- [ ] **dof_condo**
- [ ] **dcp_commercialoverlay**
- [ ] **dcp_limitedheight**
- [ ] **dcp_zoningdistricts**
- [ ] **dcp_specialpurpose**
- [ ] **dcp_specialpurposesubdistricts**
- [ ] **dcp_zoningmapamendments**
- [ ] **dcp_edesignation**

### Never Updated (Safe to ignore)

- [x] **doitt_zipcodeboundaries** (almost never updated, check [here](https://data.cityofnewyork.us/Business/Zip-Code-Boundaries/i8iw-xf4u))
- [x] **fema_firms2007_100yr**
- [x] **fema_pfirms2015_100yr**
- [x] **dcp_zoningmapindex**

### Update QAQC App 

~~- [ ] **update data-engineering-qaqc version_comparison_report in src/pluto/pluto.py with version of pluto build** (must be updated with every version of pluto [here] (https://github.com/NYCPlanning/data-engineering-qaqc/blob/main/src/pluto/pluto.py))~~

# PLUTO Improvements (corrections)

# Build CI Runs

- **[INSERPT LINKS TO RELEVANT CI RUNS HERE]**
 
# Comments

**Comment by mbh329** [comment]
Created a branch for minor PLUTO build https://github.com/NYCPlanning/db-pluto/tree/mbh-441-build-23v1.1

**Comment by mbh329** [comment]
No longer using `pluto_corrections` table, can delete this data and archive in DO

**Comment by mbh329** [comment]
@damonmcc Is there a reason why the `version.env` variables weren't updated when we built `23v1` major release of PLUTO and never checked off in the Issue template: https://github.com/NYCPlanning/db-pluto/issues/433?  I remember there being the issue with PTS but did that impact the other data?

**Comment by mbh329** [comment]
Ill check the source data versions file to confirm

**Comment by mbh329** [comment]
Nevermind - I figured out why

**Comment by mbh329** [comment]
dof_dtm no llonger lines up with the other datasets using DOF_DATA_VERSIONS as the env var, made a switch to DOF_DATA_VERSION_DTM

**Comment by mbh329** [comment]
Need to redo the issue template, as is its quite confusing. The variable names that hold the specific dates for minor builds of pluto can be obsolete quite quickly because of the various cadence we see in dataset version dates

**Comment by damonmcc** [comment]
once we receive updated zoning data we can kick off a build

**Comment by damonmcc** [comment]
[build on main](https://github.com/NYCPlanning/db-pluto/actions/runs/4894563158) successful
