### ISSUE TITLE
[build] version: 23v1.2

### ISSUE THREAD

**Issue by fvankrieken** [NYCPlanning/db-pluto#447]
### PLUTO now uses version numbering YYvMAJOR.MINOR
1. YY for the last two digits of the release year
2. MAJOR version for using the latest versions of all input data
2. MINOR version for using the latest versions of particular input data

- [x] <https://github.com/NYCPlanning/db-pluto/blob/main/pluto_build/version.env>

Make sure these are set to versions used in latest major release
- [x] DOF_WEEKLY_DATA_VERSION
- [x] DOF_CAMA_DATA_VERSION

- [x] GEOSUPPORT_VERSION
- [x] FEMA_FIRPS_VERSION
- [x] DOITT_DATA_VERSION
- [x] DOF_DATA_VERSION

- [x] DCP_COLP_VERSION
- [x] DPR_GREENTHUMB_VERSION
- [x] DSNY_FREQUENCIES_VERSION
- [x] LPC_HISTORIC_DISTRICTS_VERSION
- [x] LPC_LANDMARKS_VESRSION

- [x] PLUTO_CORRECTIONS_VERSION

### Updated with Zoning Taxlots (check [here](https://github.com/NYCPlanning/db-zoningtaxlots/actions/workflows/dataloading.yml) for latest run). Note: for a minor release of PLUTO, these will be the only datasets that will be updated.

- [x] **dof_dtm**
- [x] **dof_shoreline**
- [x] **dof_condo**
- [x] **dcp_commercialoverlay**
- [x] **dcp_limitedheight**
- [x] **dcp_zoningdistricts**
- [x] **dcp_specialpurpose**
- [x] **dcp_specialpurposesubdistricts**
- [x] **dcp_zoningmapamendments**
- [x] **dcp_edesignation**

## Update QAQC App 

~~- [ ] **update data-engineering-qaqc version_comparison_report in src/pluto/pluto.py with version of pluto build** (must be updated with every version of pluto [here] (https://github.com/NYCPlanning/data-engineering-qaqc/blob/main/src/pluto/pluto.py))~~

## Build CI Runs

- **[INSERPT LINKS TO RELEVANT CI RUNS HERE]**

**Comment by fvankrieken** [comment]
@caseysmithpgh says zoning districts will be worked on sometime this week

**Comment by caseysmithpgh** [comment]
@fvankrieken Zoning files have been QA'd and are available in edm-publishing/datasets/...

**Comment by fvankrieken** [comment]
Building in data engineering repo
- https://github.com/NYCPlanning/data-engineering/issues/5
- https://github.com/NYCPlanning/data-engineering/actions/runs/5205041860

Outputs generated
- https://cloud.digitalocean.com/spaces/edm-publishing?i=266877&path=db-pluto%2F23v1.2%2F

**Comment by fvankrieken** [comment]
gdb export missing from latest build due to typo, will rerun
