### ISSUE TITLE
Feature request: new columns indicating lot intersection of supporting DCP layers

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/db-pluto#55]
ZoLa lot detail [views](https://zola.planning.nyc.gov/lot/1/905/59) show users which layers the lot intersects with, including floodplain information, among other details. The app does this by performing spatial intersection queries on-the-fly. This is resource-intensive and inefficient. 

It would help if PLUTO could include new columns - or include a supporting data product - that joined the spatial intersections of the following supporting tables:

- [x] inclusionary_housing
- [x] transitzones
- [x] fresh_zones
- [x] waterfront_access_plan
- [x] coastal_zone_boundary
- [x] lower_density_growth_management_areas
- [x] floodplain_firm2007
- [x] floodplain_pfirm2015
- [x] mandatory_inclusionary_housing
- [x] e_designations
- [x] upland_waterfront_areas
- [x] appendixj_designated_mdistricts

Because this information changes regularly, updates to supporting layers would need to trigger a refresh of the PLUTO columns or supporting product.

**Comment by AmandaDoyle** [comment]
@allthesignals Flagging that
firm07_flag (floodplain_firm2007) , pfirm15_flag (floodplain_pfirm2015) , edesignum (e_designations) are already included in PLUTO
We'll propose a way on how we can deliver the information from the spatial intersections that you need that are not included yet.

Are you also computing the zoning district / commercial overlay information on the fly as well?

**Comment by allthesignals** [comment]
> Are you also computing the zoning district / commercial overlay information on the fly as well?

I think so!

**Comment by AmandaDoyle** [comment]
@baolingz remove floodplain_firm2007_flag,floodplain_pfirm2015_flag,e_designations_flag from output to avoid repetition, since these flags are already in PLUTO

**Comment by AmandaDoyle** [comment]
@baolingz rename sql queries so that they're prefixed with zola_ 
similar to the zoning_ sequence

**Comment by AmandaDoyle** [comment]
@baolingz Move pluto_zola_export.sql into 05_export.sh

**Comment by baolingz** [comment]
@AmandaDoyle I just updated the scripts and output.

**Comment by allthesignals** [comment]
Thanks everyone for working so hard on this1 :)
