### ISSUE TITLE
Field lengths for each field

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/db-pluto#95]
Could you please provide an output file, in whatever format is easiest, which holds the max val character length for each field in both pluto.csv and pluto_w_corrections.csv?

**Comment by AmandaDoyle** [comment]
`select table_schema, 
       table_name,
       column_name, 
       (xpath('/row/max/text()',query_to_xml(format('select max(length(%I)) from %I.%I', column_name, table_schema, table_name), true, true, '')))[1]::text::int as max_length
from information_schema.columns
where table_schema = 'public'       
  and data_type = 'text'
order by table_schema, table_name, column_name;`

Use that query format

**Comment by aferrar** [comment]
If this is the method you'd like me to use, can you provide instructions for how to actively use the query so that I know I'm not negatively impacting your db tables? Also does this return all field max values or just whichever field is specified to replace column_name because it seems like the latter? Is it possible to just have a table generated with these values in the outputs directory on jupyter lab? Thank you
